version: '3'

services:
  fe-news-client:
    build:
      context: ./fe-news-client
      dockerfile: Dockerfile
    environment:
        REACT_APP_DB_URL: http://localhost:3009/api/v1
    ports:
      - "3000:3000"   
    depends_on:
      - be-news-service
  be-news-service:
    build:
      context: ./be-news-service
      dockerfile: Dockerfile
    ports:
      - "3009:3009"   
    depends_on:
      - mongo
  mongo:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017" 
volumes:
   slack_db: