version: '3'

services:
    news-service:
      build:
        context: .
        dockerfile: Dockerfile
      image: news-service-img
      container_name: news-service
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "8080:3009"
      depends_on:
        - mongo
    mongo:
      image: mongo
      container_name: news-service-mongodb
      ports:
        - "27017:27017"